apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: amit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-deploy
  template:
    metadata:
      labels:
        app: pet-deploy
    spec:
      containers:
      - image: cloudsihmar/amit:19
        name: pet
