apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: amit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-deploy
  template:
    metadata:
      labels:
        app: pet-deploy
    spec:
      containers:
      - image: amitsharma20020508/devops:5
        name: pet
