apiVersion: v1
kind: Service
metadata:
  labels:
    app: pet-deploy
  name: prod-svc
  namespace: myapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pet-deploy
  type: NodePort
